### PR TITLE
replace tape with tap

### PR DESCRIPTION
**Pull request by gr2m**
[tape](https://www.npmjs.com/package/tape) is made for modules that work in both node & browser. [tap](https://www.npmjs.com/package/tap) is faster and works nicely with [nyc](https://www.npmjs.com/package/nyc)

Test are failing locally for me, I can't tell why, I tape/tap doesn't change
much logic wise, only timing wise. This could be code smell worth looking into

### CODE REVIEW

**Comment by jo** [comment]
I have no idea why they're failing, too.
https://travis-ci.org/eHealthAfrica/kazana-transform/jobs/91719918#L308
```
The user's map/reduce function threw an uncaught error.
You can debug this error by doing:
myDatabase.on('error', function (err) { debugger; });
Please double-check your map/reduce function.
[ReferenceError: __cov_zZj0$j38T05kpHo0lHZUNg is not defined]
```

**Comment by gr2m** [comment]
Okay, let's leave it open as a reminder, I'll look into it some other time, as this is not blocking right now

**Comment by jo** [comment]
I have rebased this, still failing. Without nyc it is passing. Maybe the kazana log output confuses nyc? Is there a way to silent the kazana logger?

**Comment by gr2m** [comment]
I got this on my list, but won’t get to look at it before Wednesday / Thursday next week

**Comment by jo** [comment]
@gr2m absolute no hurry, I just strumbled upon it.

**Comment by gr2m** [comment]
I’ve looked into it again. Somehow it seems that `server.stop()` doesn’t kill everything or it somehow interferes with `tap`’s way to figure out that a file is finshed. When you replace the last `server.stop(t.end)` with 

```js
server.stop(function () {
  t.end()
  process.exit()
})
```

then `npm test`, at least until the next file.

I fear this could be quite a time sucker. I’ve tried to combine nyc with tape but it hangs after the `registerTransformer with single transformer updates source` test. That’s how far I got with `tap` and the `process.exit()` hack, too. `nyc` does some kind of magic to make coverage work with subprocesses, I think we must do something funky somewhere that `nyc` cannot handle.

I got it working with tape & istanbul for now #16

**Comment by jo** [comment]
I have rebased it with latest changes stop fixes but it still hangs on that `registerTransformer with single transformer updates source` test.

**Comment by jo** [comment]
This is a problem with the transformer changes feed. When running with coverage, the feed responds with
```js
{ [bad_request: Something wrong with the request]
  status: 400,
  name: 'bad_request',
  message: 'Something wrong with the request',
  error: true,
  reason: 'Something wrong with the request' }
```
Then, the feed gets restarted in an endless loop. (Maybe we should question the restarting.)

When we query the changes feed without the `submissions/pending` filter (and do the filtering client side), it works as expected. I will now implement the filter client side. This also solves the problem that this filter is not yet contained in this repo.

**Comment by quesebifurcan** [comment]
Looks good to me! All tests pass locally.

**Pull request merged**
